language: go

go:
  - 1.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install tree

install:
  - go get github.com/pkg/errors
  - go get github.com/stretchr/testify
  - go get github.com/shoenig/toolkit
  - go get github.com/vektra/mockery/.../
  - hack/travis-setup.sh

before_script:
  - hack/travis-run.sh

script:
  - go generate ./...
  - go build ./...
  - go vet ./...
  - go test ./...
  - go test -race ./...