version: '3'

services:
# You will need to run `touch /tmp/dev-vault.token` first
# because otherwise docker will create a directory instead
# of mounting the token file. Isn't that great?
# Oh yeah, you'll also need to run `chmod 0666 /tmp/dev-vault.token`
# so the docker crap can edit it.
  vault:
    image: vault
    ports:
      - "8200:8200"
    environment:
      - SKIP_SETCAP=1
    tmpfs:
      - /vault/data
    volumes:
      - ./vault-config:/vault/config
      - /tmp/dev-vault.token:/home/vault/.vault-token
    networks:
      - n1

networks:
  n1:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
